---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-app
  labels:
    app: prime-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-app
  template:
    metadata:
      labels:
        app: prime-app
    spec:
      containers:
      - name: prime-container
        image: 654654617998.dkr.ecr.us-east-1.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
